Make horses and llama's fire LivingFallEvent.
CleanroomMC/Cleanroom pull request #28
Opened 2024-01-07 02:13 UTC by Ecdcaeb

Make horses and llama's fire LivingFallEvent.Fix #13 .

2024-02-24 09:40 UTC, Rongmario requested changes

2024-02-24 09:40 UTC, Rongmario commented on patches/minecraft/net/minecraft/entity/passive/AbstractHorse.java.patch
>  +        this.itemHandler = new net.minecraftforge.items.wrapper.InvWrapper(this.field_110296_bG);
Is this needed?

2024-02-24 09:40 UTC, Rongmario commented on patches/minecraft/net/minecraft/entity/passive/AbstractHorse.java.patch
> ++        p_180430_2_=evt.getDamageMultiplier();
Fix spacings please

2024-02-24 09:40 UTC, Rongmario commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +import net.minecraftforge.event.entity.living.*;
Avoid star imports.

2024-02-24 09:40 UTC, Rongmario commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +
Use the existing `onLivingFall` method.

2024-02-24 09:40 UTC, Rongmario commented on patches/minecraft/net/minecraft/entity/passive/AbstractHorse.java.patch
> ++        if (evt.isCanceled())return;
Use the existing `onLivingFall` method.

2024-02-24 09:40 UTC, Rongmario commented on patches/minecraft/net/minecraft/entity/passive/EntityLlama.java.patch
> ++        p_180430_2_=evt.getDamageMultiplier();
Same as above comments.

2024-02-25 04:12 UTC, Ecdcaeb commented on patches/minecraft/net/minecraft/entity/passive/AbstractHorse.java.patch
>  +        this.itemHandler = new net.minecraftforge.items.wrapper.InvWrapper(this.field_110296_bG);
idk， it is the old patch.

2024-02-25 12:54 UTC, Rongmario approved these changes

2024-02-25 12:55 UTC, merged